### ISSUE TITLE
Type comparison - 'SafeText' object has no attribute 'literal'

### ISSUE THREAD

**Issue by glsignal** [phrase/django-phrase#20]
Hi there!

I've been doing some work integrating Phrase with one of our Django apps recently and have run into an interesting behaviour.

First off, the library works really well to get us off the ground quickly, so thank you!

In some cases (such as the template snippet below), the `__safer_name` function in utils will be given a `SafeText` object instead of a string:

**Works fine:** 
```python
<h1>{% trans "Add" %}</h1>
```

**Throws the exception in the title (`'SafeText' object has no attribute 'literal'`)**
```python
{% trans "Add" as heading_name %}

<h1>{{ heading_name }}</h1>
```

The second case fails the type check [`type(self.name) is text_type`](https://github.com/phrase/django-phrase/blob/master/phrase/utils.py#L32) as it is not a string, and so the second branch is executed producing the exception. If we change it to `isinstance(self.name, text_type)` (so that the type check includes ancestor types) the template snippets above both work as expected and the text is rendered correctly.

From here I have a couple of questions:

1. Am I doing something wrong to produce this, or is this an unsupported way of using translated strings and Phrase together? (I can produce this in both our application and a fresh django app)

2. Would the use of `isinstance` be a sensible change to include in the library? (there are plenty of compatibility questions to be answered first, I imagine)

Finally, I'm reasonably new to python and django, so please correct me if I'm missing some knowledge from general best practice!

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
